### ISSUE TITLE
CosmosFullNode removes pod while creating VolumeSnapshot from PVC

### ISSUE THREAD

**Issue by DavidNix** [strangelove-ventures/cosmos-operator#152]
Related to https://github.com/strangelove-ventures/cosmos-operator/issues/151

We have to temporarily delete the pod while the VolumeSnapshot is created. That way, we prevent data corruption via partially written data. 

Once VolumeSnapshot is complete, we restore the pod.

Requirements:
- At least 1 healthy pod must be available and not temporarily deleted. Otherwise, snapshot feature may cause downtime.

### Tasks

- [x] Update status of CosmosFullNode with instance candidate
- [x] Fix issue where ComosFullNode and ScheduledVolumeSnapshot controllers simultaneously update fullnode's status
- [x] CosmosFullNode uses status to add/remove pod
- [x] Wait on pod deletion before progressing
