### ISSUE TITLE
CosmosFullNode: Persists the node key for life of CRD

### ISSUE THREAD

**Issue by DavidNix** [strangelove-ventures/cosmos-operator#21]
Problem: We can't be persistent peers if we often clobber the node key. 

My proposed solution is to have the controller generate the node key (assuming it's stable across all chains - need to confirm.) Then save it as a secret which never changes. The secret can be mounted into the container. 

~~Can each pod use the same secret?~~ No. Will introduce erratic p2p behavior. 

`unsafe-reset-all` may be a potential solution but requires using a PV which may be altered or deleted. 

```[tasklist]
### Tasks
- [x] Operator creates node key (do not rely on `chaind init`)
- [x] Create node key secrets
- [x] Mount secret into node container as file
- [x] Capture node ids in status subresource
- [x] Update README to highlight operator can be used as persistent peers and/or seeds
```

**Comment by DavidNix** [comment]
Prerequisite to https://github.com/strangelove-ventures/cosmos-operator/issues/42

**Comment by DavidNix** [comment]
Once this story is complete, this means CosmosFullNodes can be configured as reliable seeds and persistent peers.
