### ISSUE TITLE
Create Helm Chart for Cosmos Operator

### ISSUE THREAD

**Issue by danbryan** [strangelove-ventures/cosmos-operator#430]
# Create Helm Chart for Cosmos Operator

## Description
This issue aims to create a Helm chart for the [Cosmos Operator](https://github.com/strangelove-ventures/cosmos-operator). The Helm chart will facilitate the deployment and management of the Cosmos Operator on Kubernetes clusters.

## Subtasks
- [ ] **Research and Define Chart Structure**
  - Review the [Cosmos Operator repository](https://github.com/strangelove-ventures/cosmos-operator) to understand the necessary configurations and components.
  - Define the structure of the Helm chart, including templates, values, and Chart.yaml.

- [ ] **Create Initial Helm Chart**
  - Set up the initial Helm chart directory and file structure.
  - Create `Chart.yaml` with metadata about the chart.
  - Create a basic `values.yaml` file with default configuration values.

- [ ] **Develop Templates**
  - Create Kubernetes resource templates (`deployment.yaml`, `service.yaml`, etc.) in the `templates` directory.
  - Utilize Helm template functions to make the templates configurable via `values.yaml`.
  - Ensure templates cover all necessary resources for deploying the Cosmos Operator.

- [ ] **Define Values and Documentation**
  - Populate `values.yaml` with comprehensive configuration options.
  - Document each value in the `values.yaml` file for user reference.
  - Create a `README.md` to guide users on how to install and configure the Helm chart.

- [ ] **Testing and Validation**
  - Deploy the Helm chart in a test Kubernetes cluster.
  - Validate the deployment and functionality of the Cosmos Operator.
  - Fix any issues and ensure the Helm chart works as expected.

## References
- [Cosmos Operator GitHub Repository](https://github.com/strangelove-ventures/cosmos-operator)
- [Helm Chart Best Practices](https://helm.sh/docs/chart_best_practices/)

**Comment by nourspace** [comment]
This might be useful as all operator kube manifests are generated using Kustomize. So unless we recreate these under helm templates (duplicate), we need to somehow run the kustomize build command as part of the helm install/upgrade cycle.

https://trstringer.com/helm-kustomize/

**Comment by bizrad** [comment]
Looks like there was previously some other discussion and work done on this, linking related items
https://github.com/strangelove-ventures/cosmos-operator/issues/104
https://github.com/strangelove-ventures/cosmos-operator/pull/224

**Comment by bizrad** [comment]
After reading through the makefile it seems that the manifests are already prebuilt in the repo, but without the image version set. Please correct me if this is wrong, but It appears that this is the proper procedure to get manifests that can be checked into a git repo for gitops deployment.

```
git clone https://github.com/strangelove-ventures/cosmos-operator.git
export COSMOS_OPERATOR_VERSION=v0.22.0
git checkout tags/${COSMOS_OPERATOR_VERSION}
cd config/manager 
kustomize edit set image controller=ghcr.io/strangelove-ventures/cosmos-operator:${COSMOS_OPERATOR_VERSION}
cd ../default
kustomize build . >out.yaml
```
